### ISSUE TITLE
多消息并发处理问题

### ISSUE THREAD

**Issue by itlidaye** [tywo45/t-io#18]
一台客户端   链接500个链接 加入一个群组  每个链接  每20秒发送一条消息到群组

导致 其他电脑 新的链接 链接失败  链接不上服务器

如果 500个链接 只建立链接不发送消息       其他电脑 新的链接 正常

服务器没有任何的错误信息打印  cpu  内存占用也正常    linux 最大链接数也修改过了

这个问题如何 处理  是 tio 框架的问题嘛

**Comment by tywo45** [comment]
你参考一下tio提供的showcase（IM），那个场景和你这个类似，可以随便压测消息

**Comment by tywo45** [comment]
看你这个定时是怎么定时的，如果是Thread.sleep(200000)，那必然会导致线程全部被占用

**Comment by itlidaye** [comment]
定时 我是用的 Thread.sleep(200000)   线程全部被占用  应该也是一台客户端机器的 线程被占用吧

**Comment by itlidaye** [comment]
我的情况是  五百人在群里发消息后      其他的  客户端机 不管是  andoird ios  或者  websocket 都链接不了服务端   500人停止发送消息就可以链接了

**Comment by tywo45** [comment]
贴一下代码吧，或者直接用tio提供的showcase代码，showcase代码几万连接没点事

**Comment by itlidaye** [comment]
我测试 多链接 也是没有问题的 就是大量发消息 会有问题   下面是我服务器的 启动类 代码  我没做改动  都是继承你的类  仿照写的 

public void start(String serverIp, int serverPort) throws IOException {
		long start = System.currentTimeMillis();
		this.serverNode = new Node(serverIp, serverPort);
		channelGroup = AsynchronousChannelGroup.withThreadPool(serverGroupContext.groupExecutor);
		serverSocketChannel = AsynchronousServerSocketChannel.open(channelGroup);

		serverSocketChannel.setOption(StandardSocketOptions.SO_REUSEADDR, true);
		serverSocketChannel.setOption(StandardSocketOptions.SO_RCVBUF, 64 * 1024);

		
		
		InetSocketAddress listenAddress = null;

		if (StrUtil.isBlank(serverIp)) {
			listenAddress = new InetSocketAddress(serverPort);
		} else {
			listenAddress = new InetSocketAddress(serverIp, serverPort);
		}

		serverSocketChannel.bind(listenAddress, 0);
		
		wsServerSocketChannel=AsynchronousServerSocketChannel.open(channelGroup);

		wsServerSocketChannel.setOption(StandardSocketOptions.SO_REUSEADDR, true);
		wsServerSocketChannel.setOption(StandardSocketOptions.SO_RCVBUF, 64 * 1024);
		
		/**
		 * ws 端口
		 */
		Integer wsPort = IMBeanUtils.getImconfig().getWsServerConfig().getBindPort();
		
		wsServerSocketChannel.bind(new InetSocketAddress(wsPort) , 0);
		
		AcceptCompletionHandler acceptCompletionHandler=new AcceptCompletionHandler(serverSocketChannel,Protocol.TCP);
		
		AcceptCompletionHandler wsacceptCompletionHandler=new AcceptCompletionHandler(wsServerSocketChannel,Protocol.WEBSOCKET);
		
		//AcceptCompletionHandler acceptCompletionHandler = serverGroupContext.getAcceptCompletionHandler();
		serverSocketChannel.accept(this, acceptCompletionHandler);
		
		
		wsServerSocketChannel.accept(this, wsacceptCompletionHandler);
		
		serverGroupContext.startTime = System.currentTimeMillis();
}

public void completed(AsynchronousSocketChannel asynchronousSocketChannel, TioServer tServer) {
		TioServer tioServer=null;
		try {
			 tioServer = tServer;
			ImServerGroupContext serverGroupContext =(ImServerGroupContext) tioServer.getServerGroupContext();
			ImSessionContext sessionContext=null;
			if(Protocol.TCP==this.protocol) {
				sessionContext= new TcpSessionContext();
				sessionContext.setProtocolHandler(serverGroupContext.getTcpServerAioHandler());
			}else if(Protocol.WEBSOCKET==this.protocol) {
				sessionContext= new WsSessionContext();
				sessionContext.setProtocolHandler(serverGroupContext.getWsServerAioHandler());
			}
			
			InetSocketAddress inetSocketAddress = (InetSocketAddress) asynchronousSocketChannel.getRemoteAddress();
			String clientIp = inetSocketAddress.getHostString();
			
			
			
			if (org.tio.core.Tio.IpBlacklist.isInBlacklist(serverGroupContext, clientIp)) {
				log.warn("[{}]在黑名单中", clientIp);
				asynchronousSocketChannel.close();
				return;
			}

			if (serverGroupContext.statOn) {
				((ServerGroupStat)serverGroupContext.groupStat).accepted.incrementAndGet();
			}
			
			
			
//			

			asynchronousSocketChannel.setOption(StandardSocketOptions.SO_REUSEADDR, true);
			asynchronousSocketChannel.setOption(StandardSocketOptions.SO_RCVBUF, 64 * 1024);
			asynchronousSocketChannel.setOption(StandardSocketOptions.SO_SNDBUF, 64 * 1024);
			asynchronousSocketChannel.setOption(StandardSocketOptions.SO_KEEPALIVE, true);

			ServerChannelContext channelContext = new ServerChannelContext(serverGroupContext, asynchronousSocketChannel);
			channelContext.setClosed(false);
			channelContext.stat.setTimeFirstConnected(SystemTimer.currTime);
			channelContext.setServerNode(tioServer.getServerNode());
			
//			channelContext.traceClient(ChannelAction.CONNECT, null, null);
			
//			serverGroupContext.connecteds.add(channelContext);
			serverGroupContext.ips.bind(channelContext);
			
			channelContext.setAttribute(sessionContext);
			boolean isConnected = true;
			boolean isReconnect = false;
			if (serverGroupContext.getServerAioListener() != null) {
				if (!SslUtils.isSsl(channelContext.groupContext)) {
					try {
						serverGroupContext.getServerAioListener().onAfterConnected(channelContext, isConnected, isReconnect);
					} catch (Throwable e) {
						log.error(e.toString(), e);
					}
				}
			}

**Comment by tywo45** [comment]
你这是自己改了底层的核心代码？

**Comment by itlidaye** [comment]
我没有 改 都是  把你的代码贴过来的    写在自己的子类里




------------------ 原始邮件 ------------------
发件人: "tywo45"<notifications@github.com>; 
发送时间: 2019年5月8日(星期三) 上午10:07
收件人: "tywo45/t-io"<t-io@noreply.github.com>; 
抄送: "喂_心软是病不治要命"<1104248517@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [tywo45/t-io] 多消息并发处理问题 (#18)




你这是自己改了底层的核心代码？

**Comment by tywo45** [comment]
如果是这样做的，那暂时需要你自己去定位问题啦

**Comment by itlidaye** [comment]
我现在定位到的问题 是  多消息处理的时候  新的客户端可以链接 发送的协议 服务端可以收到处理    

但是 客户端收不到  服务端的数据

**Comment by itlidaye** [comment]
![QQ截图20190508153127](https://user-images.githubusercontent.com/15826407/57357907-b499d100-71a6-11e9-9b24-0ea752798567.jpg)
服务端 会走这段代码  有什么问题嘛

**Comment by tywo45** [comment]
客户端的线程被你Thread.sleep()占用了呀

**Comment by itlidaye** [comment]
压测的线程我也改成   ScheduledThreadPoolExecutor scheduleAtFixedRate  这个了 
而且 我的这个新客户端 不是压测的客户端   是  一个 独立的 安卓机子 和压测客户端分离的

**Comment by itlidaye** [comment]
我 同样的服务器代码 在windows 上运行 压测 没有先这个问题     这是什么原因呢 需要怎么排查

**Comment by tywo45** [comment]
这种情况，你检查一下linux的系统配置，譬如防火墙

**Comment by freeyob** [comment]
我们也遇到这个问题，而且是手机连接不上，手机只有单个连接和线程，不存在Thread.sleep()占用。不知道为啥就是连不上了，把压测客户端的300连接释放了，手机上也能连接上去了。
