### ISSUE TITLE
急！ 客户端接受一条数据时被分割成多条？

### ISSUE THREAD

**Issue by javacoderxxp** [tywo45/t-io#3]
TCP服务器返给客户端一条数据量较大的数据时，t-io客户端接受到的是多条（被分割的），如何设置缓冲区域的大小，可以一次接受较大数据?

**Comment by tywo45** [comment]
来码云吧，这里的消息我基本不看。

**Comment by tywo45** [comment]
你这个就是半包问题：https://www.t-io.org/doc/84
