### ISSUE TITLE
需求-重连机制ReconnConf，经过多次重连尝试都失败后，希望给个通知事件到ClientAioListener

### ISSUE THREAD

**Issue by 51future** [tywo45/t-io#7]
1、重连机制ReconnConf，经过多次重连尝试都失败后，希望给个通知事件到ClientAioListener；
2、发现作为客户端时ClientGroupContext extends GroupContext，经过多次重连尝试都失败后，GroupContext里的connections没有移除对应的这个通道；

**Comment by tywo45** [comment]
有的：
org.tio.core.intf.AioListener.onAfterConnected(ChannelContext channelContext, boolean isConnected, boolean isReconnect)

另外注意一下Tio.remove()和Tio.close()的区别，详见：[Tio.remove()和Tio.close()的区别](https://www.t-io.org/doc/141)

**Comment by tywo45** [comment]
`channelContext.closeMeta.setRemark(remark);
		channelContext.closeMeta.setThrowable(throwable);
		if (!isNeedRemove) {
			if (channelContext.isServer()) {
				isNeedRemove = true;
			} else {
				ClientChannelContext clientChannelContext = (ClientChannelContext) channelContext;
				if (!ReconnConf.isNeedReconn(clientChannelContext, false)) {
					isNeedRemove = true;
				}
			}
		}
		channelContext.closeMeta.setNeedRemove(isNeedRemove);

		channelContext.groupContext.closeRunnable.addMsg(channelContext);
		channelContext.groupContext.closeRunnable.execute();`

框架层不是帮你销毁了么，那个isNeedRemove = true;

**Comment by 51future** [comment]
你需不需要重连是重这里判断的
public class ReconnConf {
	private static Logger log = LoggerFactory.getLogger(ChannelContext.class);

	public static boolean isNeedReconn(ClientChannelContext clientChannelContext, boolean putIfTrue) {
		ClientGroupContext clientGroupContext = (ClientGroupContext) clientChannelContext.groupContext;
		ReconnConf reconnConf = clientGroupContext.getReconnConf();
		if (reconnConf != null && reconnConf.getInterval() > 0) {
			if (reconnConf.getRetryCount() <= 0 || reconnConf.getRetryCount() >= clientChannelContext.getReconnCount()) {
				if (putIfTrue) {
					clientChannelContext.stat.timeInReconnQueue = SystemTimer.currTime;
					reconnConf.getQueue().add(clientChannelContext);
				}
				return true;
			} else {
				log.info("不需要重连{}", clientChannelContext);
				return false;
			}
		}

		return false;
	}

org.tio.client.ConnectionCompletionHandlerd 的119行 ReconnConf.put(channelContext);

你给的那段代码，这个时候isNeedRemove都还不等于true的

**Comment by 51future** [comment]
还有，我不是说调Tio.close去关连接的问题，说的是重连的流程

**Comment by tywo45** [comment]
reconnConf.getRetryCount() <= 0 || reconnConf.getRetryCount() >= clientChannelContext.getReconnCount()

这个条件判断会挡掉重连指定次数以上的clientChannelContext，没看出毛病

**Comment by 51future** [comment]
org.tio.client.ReconnConf的isNeedReconn的reconnConf.getQueue().add(clientChannelContext);就会进行一次重连，重连失败然后会走到org.tio.client.ConnectionCompletionHandlerd 的119行ReconnConf.put(channelContext); 再判断是否重连；

3次重连都失败，org.tio.client.ReconnConf的isNeedReconn直接log.info("不需要重连{}", clientChannelContext);  那clientGroupContext.closeds和clientGroupContext.connections就没有移除掉呀！

**Comment by tywo45** [comment]
closeRunnable里会释放所有资源

public class MaintainUtils {
	
	private static final Logger log = LoggerFactory.getLogger(MaintainUtils.class);

	public static final String TEMP_DIR = "TIO_TEMP_FILE/";

	/**
	 * 彻底删除，不再维护
	 * @param channelContext
	 *
	 * @author tanyaowu
	 *
	 */
	public static void remove(ChannelContext channelContext) {
		GroupContext groupContext = channelContext.groupContext;
		if (!groupContext.isServer()) {
			ClientGroupContext clientGroupContext = (ClientGroupContext) groupContext;
			clientGroupContext.closeds.remove(channelContext);
			clientGroupContext.connecteds.remove(channelContext);
		}

		groupContext.connections.remove(channelContext);
		groupContext.ips.unbind(channelContext);
		groupContext.ids.unbind(channelContext);

		close(channelContext);
	}

**Comment by 51future** [comment]
org.tio.core.task.CloseRunnable的92行开始
try {
						if (isNeedRemove) {
							MaintainUtils.remove(channelContext);
						} else {
							ClientGroupContext clientGroupContext = (ClientGroupContext) channelContext.groupContext;
							clientGroupContext.closeds.add(channelContext);
							clientGroupContext.connecteds.remove(channelContext);
							MaintainUtils.close(channelContext);
						}
isNeedRemove为true的时候才会，需要重连这个时候，这里的isNeedRemove为false的

**Comment by tywo45** [comment]
修改了，最新代码在码云，github的代码晚上维护

https://gitee.com/tywo45/t-io

**Comment by 51future** [comment]
看了代码，觉得没有改到点上，只是在原来的基础上做了优化。
重新理下这个场景：
1、假设作为客户端去连接130.30.30.30服务器，设的3次重连；
2、连接上了130.30.30.30服务器，
      groupContext.connections 必有这个clientChannelContext
      groupContext.ips
      groupContext.ids  
3、130.30.30.30服务器停了
4、作为客户端检测到这个clientChannelContext不可用，Tio.close去关闭，此时isNeedRemove=false的
5、进入到CloseRunnable，isNeedRemove=false的， clientGroupContext.closeds会加入这个通道，步骤2的资源还是在的，ReconnConf.put(clientChannelContext);进入到第一次重连
6、重连成功与否都进入到ConnectionCompletionHandler，重连失败ReconnConf.put(channelContext);进入到再次判断是否重连，一直循环6步骤，如3次尝试都失败，就结束了。
7、步骤2和步骤5，相应的资源是否释放了？  难道步骤6的ClientChannelContext channelContext = attachment.getChannelContext();   取出来的channelContext =null，就代表
groupContext.connections
groupContext.ips
groupContext.ids 
clientGroupContext.closeds
这些资源就相应的释放了么？

**Comment by tywo45** [comment]
解决了，这次经过测试了，最新代码在码云，github的代码晚上维护

https://gitee.com/tywo45/t-io

谢谢你这么仔细地反馈问题！

**Comment by 51future** [comment]
点赞，tio越来越好

**Comment by tywo45** [comment]
> 点赞，tio越来越好

你看看这次改的代码，还真没那么容易好改，那个closeLock把我自己也坑了，IO框架就是一路踩坑

**Comment by 51future** [comment]
我只是看了下代码，没有测试，需要测下才知道。
昨天看时也有疑问，重连失败不需要重连时为什么要通过Tio.close去释放，为什么要绕到CloseRunnable，直接释放那几个资源就可以了。 当然绕了后会有个onBeforeClose通知事件，所以没在意
