### ISSUE TITLE
怎么实现多点 登陆  支持群组和单聊 收发消息 的多点登陆

### ISSUE THREAD

**Issue by itlidaye** [tywo45/t-io#8]

**Comment by tywo45** [comment]
你说的这些需求，tio全都能实现，你看t-io官网，以及牛吧云播（含APP）

**Comment by itlidaye** [comment]
Tio api 中没有  多点登陆 实现的代码   是需要改源码 才可以实现 嘛  我需要标识 一个userid 的ios 设备 和 android 设备

**Comment by tywo45** [comment]
很好解决啊：

ios的设备这样绑定：Tio.bindUser(ChannelContext channelContext, "ios_"+userid)

安卓的设备这样绑定：Tio.bindUser(ChannelContext channelContext, "android_"+userid)

**Comment by itlidaye** [comment]
这样我想过 是可以实现  只是不好把 同一 userId 关联在一起   还有 其他的方法嘛

**Comment by tywo45** [comment]
有其它方法

**Comment by itlidaye** [comment]
可以麻烦你 简单说一下方案嘛
